name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Setup Node.js
    #  uses: actions/setup-node@v3
    #  with:
    #    node-version: '18'

    # 构建客户端
    # - name: Build Client
    #   working-directory: ./next
    #   run: |
    #     npm install
    #     npm run build
    #   env:
    #     VITE_GITHUB_CLIENT_ID: ${{ secrets.GIT_OAUTH_CLIENT_ID }}

    # 构建服务端
    - name: Build Server
      working-directory: ./server
      run: |
        touch .env
        echo GIT_OAUTH_CLIENT_ID="${{ secrets.GIT_OAUTH_CLIENT_ID }}" >> .env
        echo GIT_OAUTH_CLIENT_SECRET="${{ secrets.GIT_OAUTH_CLIENT_SECRET }}" >> .env
        echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
        echo SMTP_HOST="${{ secrets.SMTP_HOST }}" >> .env
        echo SMTP_PORT="${{ secrets.SMTP_PORT }}" >> .env
        echo SMTP_USER="${{ secrets.SMTP_USER }}" >> .env
        echo SMTP_PASS="${{ secrets.SMTP_PASS }}" >> .env
    # copy client到机器
    # - name: scp client
    #   uses: youxingz/sshpass-scp-action@v3
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     user: ${{ secrets.SERVER_USERNAME }}
    #     pass: ${{ secrets.SERVER_PASSWORD }}
    #     src: "next/.next/*"
    #     dist: "next/.next"
        
    # copy server到机器
    # - name: scp server
    #   uses: youxingz/sshpass-scp-action@v3
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     user: ${{ secrets.SERVER_USERNAME }}
    #     pass: ${{ secrets.SERVER_PASSWORD }}
    #     src: "server/dist/*"
    #     dist: "server/dist"

    # copy .env 到机器
    - name: scp .env
      uses: youxingz/sshpass-scp-action@v3
      with:
        host: ${{ secrets.SERVER_HOST }}
        user: ${{ secrets.SERVER_USERNAME }}
        pass: ${{ secrets.SERVER_PASSWORD }}
        src: "server/.env"
        dist: "html-mail/server"
    
    # copy server/package.json 到机器
    # - name: scp server/package.json
    #   uses: youxingz/sshpass-scp-action@v3
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     user: ${{ secrets.SERVER_USERNAME }}
    #     pass: ${{ secrets.SERVER_PASSWORD }}
    #     src: "server/package.json"
    #     dist: "server"

    # 重启服务
    # - name: Restart Application
    #   uses: matheusvanzan/sshpass-action@v1
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USERNAME }}
    #     password: ${{ secrets.SERVER_PASSWORD }}
    #     run: |
    #       cd /root/server
    #       npm install --production
    #       pm2 restart 0

    # 拉代码
    - name: Restart Application
      uses: matheusvanzan/sshpass-action@v1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        run: |
          source ~/.zshrc
          cd /root/html-mail
          git pull
          cd next
          npm i
          npm run build
          pm2 reload my-nextjs-app
          cd ../server
          npm i
          npm run build
          pm2 reload my-nestjs-app
    